const employees = [
{id: 0, linkedInId: 2650987, displayName: "Fred Lintz", image: "https://upload.wikimedia.org/wikipedia/en/a/ae/RonSwanson.jpg", title: "Full Stack Web Ninja", bio: "Super chill, superfly, super coder.", email: "fred.lintz5@gmail.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 1, linkedInId: 92830987, displayName: "Ed Quintana", image: "https://upload.wikimedia.org/wikipedia/en/0/02/Ben_Wyatt_Parks_%26_Rec.jpg", title: "Full Stack Web Sensai", bio: "I eat coders like you for breakfast", email: "ed@email.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 2, linkedInId: 8375987,  displayName: "Ash Rotman", image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Tom_Haverford.jpg", title: "Full Stack Web Yoda", bio: "#makingWebsites #crushingCoffees", email: "ash@email.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 3, linkedInId: 9843597,  displayName: "Megan Landahl", image: "https://az616578.vo.msecnd.net/files/2016/03/03/635925739163844606479993529_lp.png", title: "Full Stack Web Czar", bio: "I bleed in binary", email: "megan@email.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 1, linkedInId: 92830987, displayName: "Ed Quintana", image: "https://upload.wikimedia.org/wikipedia/en/0/02/Ben_Wyatt_Parks_%26_Rec.jpg", title: "Full Stack Web Sensai", bio: "I eat coders like you for breakfast", email: "ed@email.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 0, linkedInId: 2650986, displayName: "Fred Lintz", image: "https://upload.wikimedia.org/wikipedia/en/a/ae/RonSwanson.jpg", title: "Full Stack Web Ninja", bio: "Super chill, superfly, super coder.", email: "fred.lintz5@gmail.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 3, linkedInId: 9843596,  displayName: "Megan Landahl", image: "https://az616578.vo.msecnd.net/files/2016/03/03/635925739163844606479993529_lp.png", title: "Full Stack Web Czar", bio: "I bleed in binary", email: "megan@email.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 2, linkedInId: 8375986,  displayName: "Ash Rotman", image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Tom_Haverford.jpg", title: "Full Stack Web Yoda", bio: "#makingWebsites #crushingCoffees", email: "ash@email.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []},
{id: 0, linkedInId: 2650985, displayName: "Fred Lintz", image: "https://upload.wikimedia.org/wikipedia/en/a/ae/RonSwanson.jpg", title: "Full Stack Web Ninja", bio: "Super chill, superfly, super coder.", email: "fred.lintz5@gmail.com", skills: ['html5', 'css', 'javascript', 'react', 'mongo'], searchable: true, matches: [], connections: [], denied: []}
]


module.exports = employees;